apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "chart.fullname" . }}-config
spec:
  refreshInterval: {{ .Values.secrets.store.refresh }}
  secretStoreRef:
    kind: {{ .Values.secrets.store.kind }}
    name: {{ .Values.secrets.store.name }}
  target:
    name: {{ include "chart.fullname" . }}-config
    template:
      templateFrom:
        - configMap:
            name: {{ include "chart.fullname" . }}-config-template
            items:
              - key: {{ .Values.config.name }}.yaml
  dataFrom:
    - extract:
        key: {{ .Values.secrets.name }}
