---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "chart.fullname" . }}-config
spec:
  refreshInterval: {{ .Values.secrets.store.refresh }}
  secretStoreRef:
    kind: {{ .Values.secrets.store.kind }}
    name: {{ .Values.secrets.store.name }}
  target:
    name: {{ include "chart.fullname" . }}-config
    template:
      templateFrom:
        - configMap:
            name: {{ include "chart.fullname" . }}-config-template
            items:
              - key: {{ .Values.config.name }}.yaml
  dataFrom:
    - extract:
        key: {{ .Values.secrets.name }}
