// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"

	"github.com/google/uuid"
)

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Hash      string
	CreatedAt int64
	ExpiresAt int64
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	Admin     bool
	CreatedAt int64
	UpdatedAt int64
	DeletedAt sql.NullInt64
}
