apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config-template
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{ .Values.config.name }}.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
