{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ include "chart.fullname" . }}-api
spec:
  endpoints:
  - honorLabels: false
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: /metrics
    targetPort: {{ .Values.config.telemetry.metrics.port }}
  jobLabel: {{ .Release.Name }}-api
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
{{- end }}
