name: Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      packages: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get chart version
        run: |
          CHART_VERSION=$(cat chart/Chart.yaml | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+$")
          echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_ENV

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push chart
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: go-template-helm
          repository: henrywhitaker3
          tag: "v${{ env.CHART_VERSION }}"
          path: chart
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'
